# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  install-dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update or install NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: app-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  vercel-deploy:
    build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          name: Vercel Prod Deploy
          command: vercel --prod --build-env REACT_APP_BASEURL=https://rickandmortyapi.com/api/ --name $VERCEL_PROJECT_NAME --scope $VERCER_SCOPE --token=$VERCEL_TOKEN --yes
workflows:
  version: 2
  deploy-reactapp:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - develop
      - vercel-deploy:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop
